### ISSUE TITLE
Example for Video

### ISSUE THREAD

**Issue by puppeteer701vungle** [InteractiveAdvertisingBureau/Open-Measurement-JSClients#12]
In the example you are setting the creative type to `htmlVideo` but in constants there is not mention of `htmlVideo`.

Example:
https://github.com/InteractiveAdvertisingBureau/Open-Measurement-JSClients/blob/207f271072773c83f9b857c9b45f80be5f235e29/creatives/video/omid_video_creative_session_main.js#L10

https://github.com/InteractiveAdvertisingBureau/Open-Measurement-JSClients/blob/d1f08a1e44e102519d013e2b6b9d7fe5c6c4a00b/src/common/constants.js#L412

Which is the correct value for a video creative type?

**Comment by juo007** [comment]
Thanks for bringing this up. It should `video`
