### ISSUE TITLE
npm run buildDeps is not working

### ISSUE THREAD

**Issue by LeeHyungGeun** [InteractiveAdvertisingBureau/Open-Measurement-JSClients#14]
`npm run buildDeps` command in `reference-app-web` is not working with following error

![image](https://user-images.githubusercontent.com/2471651/102598177-f6e70a80-415e-11eb-8b38-29d58835a13c.png)

and it seems there is no `build-web-service` and `build-domain-loader` scripts in package.json of root
![image](https://user-images.githubusercontent.com/2471651/102598346-3ca3d300-415f-11eb-9d27-dca65fdd0cbd.png)

**Comment by nlehrer** [comment]
This is working as intended; please see the `README` of `reference-app-web`. When in this repository (JSClients) rather than the upstream one (SDKJS), there is a different set of steps instead of running `buildDeps`.
