### ISSUE TITLE
Error in Open-Measurement-SDKJS documentation points to wrong interfaces

### ISSUE THREAD

**Issue by mog** [InteractiveAdvertisingBureau/Open-Measurement-JSClients#19]
Hey,

While implementing OM for Web, I noticed two problems in the documenation at https://interactiveadvertisingbureau.github.io/Open-Measurement-SDKJS/
As there's no clear way given to contact anyone responsible, I assume it's okay to raise the issue here - however please feel free to move it to the correct location or give me pointers to do so myself.

At _4. Create and Start the AdSession_:
`adSession.setVideoElement(VIDEO_ELEMENT)` should be `context.setVideoElement(VIDEO_ELEMENT)`

At _5. Signal Ad and Video Events_:
`videoEvents.loaded(vastProperties)` should be `adEvents.loaded(vastProperties)`

Take care, and thanks!

**Comment by nlehrer** [comment]
These were both fixed at some point last year. Thanks for reporting!
