### ISSUE TITLE
`session.start` and `session.finish` missing in session API

### ISSUE THREAD

**Issue by mmatzanke** [InteractiveAdvertisingBureau/Open-Measurement-JSClients#5]
Hey,

I've tried to integrate the JS client into our web player but I've multiple issues due to lacks within the documentation for web. Could you please help me? I will try to give you an example code where the session somehow is/can not be started:

```js
import { OmidSessionClient } from './omid-session-client-v1.js';
const {
  VerificationScriptResource,
  Partner,
  Context,
  AdSession,
  AdEvents,
  VideoEvents
} = OmidSessionClient;

const verificationScriptResource = new VerificationScriptResource(
          resourceUrl,
          vendorKey,
          verificationParameters
        );
const partner = new Partner(config.omPartnerName, VERSION);
const context = new Context(partner, [verificationScriptResource]);
context.setVideoElement(videoElement);
context.setSlotElement(domNode);
const session = new AdSession(context);
const adEvents = new AdEvents(session);
const videoEvents = new VideoEvents(session);
session.registerSessionObserver(event => {
      // it never gets here
});

// Here I'm missing the session.start api or similar and I don't know how to start the session from the player side

adEvents.impressionOccurred(); // throws that session is not started
```
Could you give me a hint what's going wrong please?

Regards,
Martin

**Comment by sametozcan** [comment]
Hello Martin,

We are suffering from the same problem. Were you able to find a way to start session?

Regards,
Samet

**Comment by sametozcan** [comment]
Anything new here?

**Comment by puppeteer701vungle** [comment]
I think ImpressionOccured should be placed inside registerSessionObserver.

**Comment by gvan** [comment]
If you looked at this instruction https://interactiveadvertisingbureau.github.io/Open-Measurement-SDKAndroid/#8-start-the-session, then adSession.start(); should be invoked from a native Java code of your Android application/sdk:

> Start the session in the native layer before signaling any events in the JS layer.

> `adSession.start();`

I see that IAB plans to release OMSDK for Web Video at this month https://iabtechlab.com/iab-tech-lab-expands-omsdk-scope-to-include-web-video/

**Comment by nlehrer** [comment]
The OM SDK for Web is now supported. Please see https://interactiveadvertisingbureau.github.io/Open-Measurement-SDKJS/
When using the OM SDK for Web, the JS `AdSession` API includes `start` and `finish` methods (see the section "Create and Start the AdSession").
